### ISSUE TITLE
🔧 피드 신고하기 Props Drilling

### ISSUE THREAD

**Issue by BangDori** [CollaBu/pennyway-client-webview#67]
## 수정 목적

신고하기 API를 활용하기 위해 Props로 전달해주는 과정에서 Props Drilling이 발생하여 이 문제를 해결하고자 함.

## 수정 코드

- src/widgets/feed-main-list/ui/Feed.tsx
- src/widgets/feed-kebab/ui/FeedKebabButton.tsx
- src/widgets/feed-kebab/ui/KebabMenu.tsx
- src/features/feed-reports/ui/FeedReportsForm.tsx
- src/features/feed-reports/api/useSubmitReports.tsx

## 할 일 목록

- [ ] Props Drilling 문제 해결하기
- [x] 동시에 여러 피드의 KebabMenuList를 펼칠 수 있는 문제 해결하기

## 설명

현재 신고하기 API를 적용하는 부분에 있어 다음과 같이 props drilling이 발생하고 있습니다.

> Feed -> FeedKebabButton -> KebabMenu -> FeedReportsForm -> useSubmitReports

위와 같은 컴포넌트의 연결은 Props Drilling으로 인한 컴포넌트들의 결합성이 강해져서, 수정에 어려움을 겪을 수 있습니다.

제가 생각한 방법은 Zustand를 이용하여 feedId와 onClose를 전역 상태로 관리하는 방법입니다! 아직 구체적인 방안에 대해서 계획하지는 않았지만, 혹시 좋은 의견 있으시다면 의견 제시해주시면 감사하겠습니다!

**Comment by Legitgoons** [comment]
여러 방면으로 고민해봤는데, 저 역시도 5뎁스나 props drilling이 발생한다면 전역 상태로 넘기는게 가장 적절해보입니다.

**Comment by BangDori** [comment]
@Legitgoons 

피드 신고하기에서 Props drilling이 발생한 문제에 대해서 다시 생각을 해봤는데, 피드 신고하기에 한해서 전역 상태로 관리하는 건 다른 모달창에 대해서도 전역 상태로 관리해야 할 것 같다는 생각이 들어요! 만약 이렇게 된다면 모달창들을 관리하는 다양한 전역 상태가 만들어지게 되면, 화면에 표시되는 모달창이 단 1개라는 점을 유일성을 보장해주기에도 어려울 것 같구요. 😵‍💫

그래서 제가 생각하기에는, 케밥메뉴부터 시작해서 신고하기나 이런 기타 등등의 모달창 전체를 관리할 수 있는 전역 상태가 하나 있으면 좋을 것 같다는 생각이 드는데, 혹시 어떻게 생각하시나요?

**Comment by Legitgoons** [comment]
@BangDori 
좋은 방법인 것 같습니다! 저도 Props drilling 해결을 위해서 `피드 신고하기` 모달만을 전역 상태로 관리했다가 만약 다른 모달 창과 동시에 랜더링되는 이슈가 발생한다면...? 이라는 불안감이 있었습니다. 

하지만, 모달 창 전체의 상태를 전역으로 관리한다면, 하면 모달 창의 유일성을 확실하게 지켜줄 수 있겠네요!

**Comment by BangDori** [comment]
넵!! 그럼 모달창 전체를 관리하는 전역 상태를 하나 만들어서 관리하는 방식으로 해당 이슈 처리하겠습니다!
