### ISSUE TITLE
🐛 Profile 페이지 스크롤 버그

### ISSUE THREAD

**Issue by Legitgoons** [CollaBu/pennyway-client-webview#81]
## 버그 내용
- Profile 페이지 스크롤이 최하단에서 시작

## 버그 위치
- src/pages/profile/ui/ProfileMainPage.tsx

## 재현
1. iPhone-layout의 경우
  - Feed의 게시글 중 최상위 게시글(Feed Content 1 by 강병준)이 아니라면 최하단에서 시작
![image](https://github.com/CollaBu/pennyway-client-webview/assets/101088491/4ffb6b93-587a-457d-a33c-ada9add793e5)

2. 일반 화면의 경우
    - Feed의 게시글 중 최상위 게시글이 아니고, 첫 방문이 아닐 경우(이미 랜더링 된 페이지일 경우) 최하단에서 시작
 
- 추측되는 원인
  - 이전 페이지에서의 스크롤 위치가 유지되는 것으로 추측됩니다. 다만 `뒤로 가기`가 아니라 새로운 페이지로 이동할 경우 스크롤 위치가 최상단이 되는 것이 기본 설정인 것으로 알기에, 조금 더 찾아볼 필요가 있습니다.
  - 또한 iPhone-layout의 경우에는 최상위 피드의 Profile이 아니라면 처음 방문하는 페이지도 늘 최하단에서 시작되기에 iPhone-Layout의 경우 다른 원인이 있을 수 있습니다. 

## 할일
- [x] ProfilePage의 스크롤이 최상단에서 시작되도록 수정

**Comment by BangDori** [comment]
문제가 발생한 원인에 대해 고려해보았는데, SPA로 인해 페이지 이동이 아닌 컴포넌트 간의 전환으로 인해 발생한 문제인 것 같습니다.

해당 문제를 해결하기 위해서는 프로필 페이지 전환 시 스크롤 위치를 수동으로 조정해야 할 것 같습니다.

**Comment by Legitgoons** [comment]
SPA 컴포넌트 전환이 문제인 것 같습니다. routers/index.ts내부에서 같은 children안에 해당 컴포넌트를 정의했기에 스크롤 위치가 고정되는 것으로 보입니다. 
```tsx
const root: RouteObject[] = [
  {
    path: '/',
    element: <IPhoneLayout />,
    children: [
      { index: true, element: <FeedMainPage /> },
      { path: 'users/:userId', element: <ProfileMainPage /> },
    ],
  },
];
```

**Comment by BangDori** [comment]
children이 아닌, siblings로 두시고 나서 결과 알려주시면 감사하겠습니다!

**Comment by Legitgoons** [comment]
SPA가 원인인 것은 맞지만, index.ts 수정으로는 해결되지 않았습니다. React Router에서 해당 이슈를 위해 지원하는 [ScrollRestoration](https://reactrouter.com/en/main/components/scroll-restoration#scrollrestoration-)을 통해서 해결하였습니다.

**Comment by BangDori** [comment]
넵 확인하였습니다.

프로필 페이지 진입 시에는 스크롤 위치를 항상 상단에 고정하여야 하지만, 메인 페이지에서는 사용자의 스크롤 위치를 기억하고 있어야 한다는 점을 고려하면서 적용해주시면 감사하겠습니다!
