### ISSUE TITLE
✨ User API 닉네임 / 이름 분리

### ISSUE THREAD

**Issue by Legitgoons** [CollaBu/pennyway-client-webview#89]
## 추가할 기능
- User API에 `닉네임`과 `이름` 추가
- 추가한 사항에 따라 기존 로직 수정

## 할 일 목록
- [x] User API 닉네임, 이름 분리
- [x] 기존 User API 사용 로직 수정

## 설명
- User API에 `닉네임`과 `이름`이 별개로 되어 있지않고 `name`이라는 하나의 키워드만 있습니다.

**Comment by BangDori** [comment]
이슈 확인했습니다~ PM & 디자인 팀과 협의 후에 진행해주세요!
