### ISSUE TITLE
🔧 CD Pipeline의 적용 시점

### ISSUE THREAD

**Issue by BangDori** [CollaBu/pennyway-client-webview#9]
## 논의 주제

- CD Pipeline의 적용 시점

## 논의 내용

현재 github flow에 맞춰 main브런치와 작업 브런치 두개의 브런치로 관리하고 있습니다. CI 파이프라인은 main 브랜치에 pull request가 발생하였을 때 trigger 되고, CD 파이프라인은 main 브랜치에 push 되었을 때 trigger 됩니다.

논의하고자 하는 점은 **CD 파이프라인을 언제 적용시켜야 하는가**입니다. 그 이유는 만약 push되었을 때 CD Pipeline이 fail 되면 최신 버전이 정상적으로 반영되지 않는 문제가 발생합니다. 그렇다면 이 문제에 대해서 어떻게 해결해야 할까요?

제가 생각한 방법은 아래와 같습니다.

<div align="center">
  <img src="https://github.com/CollaBu/pennyway-client-webview/assets/44726494/0ad604d6-b4de-4395-b635-9e3172c6982e" width="600" />
</div>

우선 제가 생각한 방법은 위 3가지 인데, 혹시 더 좋은 방법이 있다면 의견을 남겨주셔도 좋을 것 같습니다!

**Comment by Legitgoons** [comment]
2번 방안 -> 1번 방안 -> 3번 방안 순으로 적합해보입니다.

- 우선 2번이 에러가 발생할 수 있는 코드가 메인 브랜치에 병합되는 것을 막을 수 있다는 점에서 가장 적절해보입니다.
- 또한 지나치게 많은 PR이 생겨난다면 오히려 집중도를 떨어트릴 수 있기에, 여러 부분에 걸쳐 있는 심각한 이슈가 아니라면 하나의 PR안에서 해결하는 것이 좋다고 생각합니다. 
- 하지만 2번 방안이 불가능하다면, 1번 방안도 차선으로 나쁘지 않다고 생각합니다.
- 3번 방안은 매번 트리거를 작동시켜야한다는 점에서 번거롭고, 기억력 이슈가 터질수도 있어 여러 문제점이 생길 수 있을 듯 합니다.

이 외 당장 추가적으로 생각나는 방안은 따로 없습니다.

**Comment by BangDori** [comment]
@Legitgoons 

저는 1번 방안에 대해 생각해보긴 했었습니다!

main 브랜치에 push되었다는 것은 어떻게 해석해보면, `Pull Request에 대한 테스트와 코드 리뷰가 완료되었으며 기능에 대한 문제가 발견되지 않았다.`라고 해석할 수 있을 것 같습니다.

그렇기 때문에 기능 추가에 대한 브랜치는 제 역할을 다 하였다고 생각하기에 병합하고, 배포 에러가 발생하게 된다면 이에 대한 수정 작업을 위해 브랜치를 생성하는 것도 괜찮다는 생각이 듭니다.

어떤 방법으로 가는게 가장 좋을까요?!

**Comment by Legitgoons** [comment]
@BangDori 

브랜치를 기능 추가의 관점에서 본다면 에러 처리를 위한 브랜치를 추가적으로 만드는 것도 나쁘지 않아 보입니다.
1번 방안으로 가시죠 :)

**Comment by BangDori** [comment]
넵! 해당 Issue에 대해서는 Close 하겠습니다.

1번 방안으로 가다가, 추후에 동일한 Issue가 발생하였을 때 그 때 Reopen 하여 다시 의견을 나누어보면 좋을 것 같습니다.

좋은 의견 감사드립니다 :)
